### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by architshukla** [architshukla/brotli-cli#1]

**Comment by shashankrao** [comment]
Do you intend to do all of this in Python from scratch or just use wrappers to [google/brotli](https://github.com/google/brotli)

**Comment by architshukla** [comment]
I'm intending this one to be a node CLI using an existing brotli library (implementation is in this [branch](https://github.com/architshukla/brotli-cli/tree/dev/arshukla/compress) right now). Just wanted a quick CLI to pre-compress files because most web servers don't support brotli compression without a plugin right now.

That said, it would be fun to try the core implementation if you are in. 😛
